<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="8" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="330776" started-at="2020-06-20T12:26:48Z" finished-at="2020-06-20T12:32:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="330776" started-at="2020-06-20T12:26:48Z" finished-at="2020-06-20T12:32:19Z">
      <class name="TestCases.SystemTest">
        <test-method status="PASS" signature="SystemTest1(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest1" duration-ms="73712" started-at="2020-06-20T17:56:49Z" data-provider="getAwsTestData" finished-at="2020-06-20T17:58:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra90@gmail.com, Password=M@nju_123, Comment =Valid Credentials, PageTitle =AWS Management Console }]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest1 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="580" started-at="2020-06-20T17:58:03Z" finished-at="2020-06-20T17:58:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="138" started-at="2020-06-20T17:58:03Z" finished-at="2020-06-20T17:58:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest1(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest1" duration-ms="26971" started-at="2020-06-20T17:58:03Z" data-provider="getAwsTestData" finished-at="2020-06-20T17:58:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra90@gmail.com, Password=Manju_123, Comment =Invalid Password, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest1(SystemTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest1 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="70" started-at="2020-06-20T17:58:30Z" finished-at="2020-06-20T17:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="89" started-at="2020-06-20T17:58:31Z" finished-at="2020-06-20T17:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest1(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest1" duration-ms="19653" started-at="2020-06-20T17:58:31Z" data-provider="getAwsTestData" finished-at="2020-06-20T17:58:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra@gmail.com, Password=M@nju_123, Comment =Invalid UserId, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest1(SystemTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest1 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="121" started-at="2020-06-20T17:58:50Z" finished-at="2020-06-20T17:58:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="138" started-at="2020-06-20T17:58:50Z" finished-at="2020-06-20T17:58:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest1(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest1" duration-ms="28152" started-at="2020-06-20T17:58:51Z" data-provider="getAwsTestData" finished-at="2020-06-20T17:59:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra@gmail.com, Password=Manju_123, Comment =Invalid Credentials, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest1(SystemTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest1 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="73" started-at="2020-06-20T17:59:19Z" finished-at="2020-06-20T17:59:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="93" started-at="2020-06-20T17:59:19Z" finished-at="2020-06-20T17:59:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="SystemTest2(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest2" duration-ms="92373" started-at="2020-06-20T17:59:19Z" data-provider="getAwsTestData" finished-at="2020-06-20T18:00:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra90@gmail.com, Password=M@nju_123, Comment =Valid Credentials, PageTitle =AWS Management Console }]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest2 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="150" started-at="2020-06-20T18:00:51Z" finished-at="2020-06-20T18:00:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="360" started-at="2020-06-20T18:00:51Z" finished-at="2020-06-20T18:00:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest2(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest2" duration-ms="25653" started-at="2020-06-20T18:00:52Z" data-provider="getAwsTestData" finished-at="2020-06-20T18:01:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra90@gmail.com, Password=Manju_123, Comment =Invalid Password, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest2(SystemTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest2 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="66" started-at="2020-06-20T18:01:17Z" finished-at="2020-06-20T18:01:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="171" started-at="2020-06-20T18:01:18Z" finished-at="2020-06-20T18:01:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest2(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest2" duration-ms="25618" started-at="2020-06-20T18:01:18Z" data-provider="getAwsTestData" finished-at="2020-06-20T18:01:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra@gmail.com, Password=M@nju_123, Comment =Invalid UserId, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest2(SystemTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest2 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="53" started-at="2020-06-20T18:01:43Z" finished-at="2020-06-20T18:01:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="126" started-at="2020-06-20T18:01:43Z" finished-at="2020-06-20T18:01:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="SystemTest2(java.util.Hashtable)[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="SystemTest2" duration-ms="35392" started-at="2020-06-20T18:01:44Z" data-provider="getAwsTestData" finished-at="2020-06-20T18:02:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{UserId=ddogra@gmail.com, Password=Manju_123, Comment =Invalid Credentials, PageTitle =Amazon Web Services Sign-In}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User email or password incorrect ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User email or password incorrect 
	at org.testng.Assert.fail(Assert.java:94)
	at baseClasses.PageBaseClass.reportFail(PageBaseClass.java:49)
	at PageClasses.LandingPage.doLogin(LandingPage.java:78)
	at TestCases.SystemTest.SystemTest2(SystemTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SystemTest2 -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="flushReports" is-config="true" duration-ms="56" started-at="2020-06-20T18:02:19Z" finished-at="2020-06-20T18:02:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.SystemTest@27a8c74e]" name="tearDown" is-config="true" duration-ms="175" started-at="2020-06-20T18:02:19Z" finished-at="2020-06-20T18:02:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.SystemTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
